'use strict';var e=this,g=function(a,b){a=a.split(".");var c=e;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b};var h=function(a,b){return 0==a.lastIndexOf(b,0)},l=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c},m=function(a){return a.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},n=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},p=function(a,b){for(var c=b.length,d=0;d<c;d++){var f=1==c?b:b.charAt(d);if(a.charAt(0)==f&&a.charAt(a.length-1)==f)return a.substring(1,a.length-1)}return a};var q=function(a,b){this.b=b||"";this.a=a||""},r=/"/g,u=/\\"/g,aa=/\\/g,ba=/\\\\/g,ca=/^[+a-zA-Z0-9_.!#$%&'*\/=?^`{|}~-]+@([a-zA-Z0-9-]+\.)+[a-zA-Z0-9]{2,63}$/;q.prototype.getName=function(){return this.b};q.prototype.toString=function(){var a=this.getName();a=a.replace(r,"");var b;a:{for(b=0;13>b;b++)if(-1!=a.indexOf('()<>@:\\".[],;'[b])){b=!0;break a}b=!1}b&&(a='"'+a.replace(aa,"\\\\")+'"');return""==a?this.a:""==this.a?a:a+" <"+this.a+">"};
var w=function(a,b){if('"'!=a.charAt(b))return!1;var c=0;for(--b;0<=b&&"\\"==a.charAt(b);b--)c++;return 0!=c%2};var da=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;/*

 Copyright 2011 Google Inc. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var x,y,z,A,B,C,D,E,ea="https://accounts.google.com/SecondFactor https://accounts.google.com/b/0/VerifiedPhoneInterstitial https://accounts.google.com/signin/newfeatures https://accounts.google.com/signin/selectchallenge https://accounts.google.com/signin/challenge https://accounts.google.com/signin/privacyreminder https://accounts.google.com/signin/v2/challenge/ipp".split(" "),fa=["https://accounts.google.com/signin/challenge/sl/password","https://accounts.google.com/signin/challenge/pwd/1"],F=["One account. All of Google.",
"Sign in with your Google Account","<title>Sign in - Google Accounts","//ssl.gstatic.com/accounts/ui/logo_2x.png"],G=['<input id="Passwd" name="Passwd" placeholder="Password" class="" type="password">','<input id="Passwd" name="Passwd" type="password" placeholder="Password" class="">','<input id="signIn" name="signIn" class="rc-button rc-button-submit" ','<div class="editpasswdpage main content clearfix">'],H=["accounts.google.com","login.corp.google.com","myaccount.google.com"],I="",J="",K=!1,L=
!1,M=!1,N=!1,S=function(){if(M&&N&&!h(I,"https://accounts.youtube.com/accounts/CheckConnection")){if(x&&h(I,x)){var a=document.querySelector(y);a?(chrome.runtime.sendMessage({action:"deletePossiblePassword"}),a.addEventListener("submit",ha,!0)):chrome.runtime.sendMessage({action:"savePossiblePassword"})}else if(h(I,"https://accounts.google.com/speedbump/changepassword")){var b;chrome.runtime.sendMessage({action:"getEmail"},function(a){b=a});var c=document.getElementById("gaia_changepasswordform");
c.addEventListener("submit",function(){chrome.runtime.sendMessage({action:"setPossiblePassword",email:b,password:c.Passwd.value})},!0)}else h(I,"https://accounts.google.com/")?ia()?chrome.runtime.sendMessage({action:"savePossiblePassword"}):(chrome.runtime.sendMessage({action:"deletePossiblePassword"}),(a=document.querySelector("#view_container > form"))&&document.getElementById("Email")?a.addEventListener("submit",ja,!0):document.getElementById("hiddenEmail")&&document.getElementsByName("password")&&
(document.getElementById("passwordNext").addEventListener("click",function(){O(null)}),document.getElementById("passwordNext").addEventListener("keydown",function(a){32==a.keyCode&&O(a)},!0),document.addEventListener("keydown",function(a){13==a.keyCode&&O(a)},!0),window.onbeforeunload=O)):h(I,"https://myaccount.google.com/signinoptions/password")?(chrome.runtime.sendMessage({action:"deletePossiblePassword"}),window.onload=function(){var a=document.querySelectorAll("div[role=button]");a=a[a.length-
1];a.addEventListener("click",P,!0);a.addEventListener("keydown",function(a){32==a.keyCode&&P()},!0);document.addEventListener("keydown",function(a){13==a.keyCode&&P()},!0)}):(!Q()&&ka()&&chrome.runtime.sendMessage({action:"looksLikeGoogle",url:I,referer:J,securityEmailAddress:C}),chrome.runtime.sendMessage({action:"savePossiblePassword"}));chrome.runtime.sendMessage({action:"statusRequest"},function(a){K=!1;R(a)})}},ia=function(){var a=I,b=!1;ea.forEach(function(c){h(a,c)&&(b=!0)});b&&fa.forEach(function(c){h(a,
c)&&(b=!1)});return b},R=function(a){try{var b=JSON.parse(a);if(b.passwordLengths&&0==b.passwordLengths){K=!1;return}}catch(c){}x&&h(I,x)||h(I,"https://accounts.google.com/")||Q()?K=!1:(K=!0,L||chrome.storage.local.get("allowed_hosts",function(a){var b=window.location.origin;0<Object.keys(a).length&&a.allowed_hosts[b]&&(K=!1)}),T())},U=function(a){K&&a.isTrusted&&chrome.runtime.sendMessage({action:"handleKeypress",keyCode:a.charCode,typedTimeStamp:a.timeStamp,url:I,referer:J,looksLikeGoogle:T()})};
g("passwordalert.handleKeypress",U);var V=function(a){K&&a.isTrusted&&chrome.runtime.sendMessage({action:"handleKeydown",keyCode:a.keyCode,shiftKey:a.shiftKey,typedTimeStamp:a.timeStamp,url:I,referer:J,looksLikeGoogle:T()})};g("passwordalert.handleKeydown",V);var W=function(a){!K||void 0===a.clipboardData||a.timeStamp<=D||(D=a.timeStamp,chrome.runtime.sendMessage({action:"checkString",password:a.clipboardData.getData("text/plain").trim(),url:I,referer:J,looksLikeGoogle:T()}))};
g("passwordalert.handlePaste",W);
var ha=function(){var a=document.querySelector(A);var b=document.querySelector(z);a&&!a.value||b&&!b.value?(console.log("SSO data is not filled in."),a=!1):a=!0;a&&(a=document.querySelector(A).value,b=document.querySelector(z).value,-1==a.indexOf("@")&&(a+="@"+B.split(",")[0].trim()),chrome.runtime.sendMessage({action:"setPossiblePassword",email:a,password:b}))},ja=function(){var a=document.getElementById("gaia_loginform"),b=a.Email?n(a.Email.value.toLowerCase()):"";a=a.Passwd?a.Passwd.value:"";L&&
!X(b)||0==(null==a?"":String(a)).length||chrome.runtime.sendMessage({action:"setPossiblePassword",email:b,password:a})},O=function(){var a=document.getElementById("hiddenEmail");a=a?n(a.value.toLowerCase()):"";var b=document.getElementsByName("password");b&&1==b.length&&(b=b[0].value,a&&b&&(L&&!X(a)||0==(null==b?"":String(b)).length||chrome.runtime.sendMessage({action:"setPossiblePassword",email:a,password:b})))},P=function(){var a=Date.now();window.onbeforeunload=function(){if(!(1E3<Date.now()-a)){var b=
document.querySelector("div[data-config]").getAttribute("data-config"),c=b.indexOf('",["')+4;b=b.substring(c,b.indexOf('"',c));for(var d=c="",f=0;f<b.length;){var k=b.charAt(f);var v='"<(['.indexOf(k);if(-1!=v&&!w(b,f)){v='">)]'.charAt(v);for(var t=b.indexOf(v,f+1);0<=t&&w(b,t);)t=b.indexOf(v,t+1);k=0<=t?b.substring(f,t+1):k}"<"==k.charAt(0)&&-1!=k.indexOf(">")?d=k.substring(1,k.indexOf(">")):""==d&&(c+=k);f+=k.length}""==d&&-1!=c.indexOf("@")&&(d=c,c="");c=m(c);c=p(c,"'");c=p(c,'"');c=c.replace(u,
'"');c=c.replace(ba,"\\");d=m(d);c=new q(d,c);ca.test(c.a)?chrome.runtime.sendMessage({action:"setPossiblePassword",email:b,password:document.querySelector('input[aria-label="New password"]').value}):console.log("Parsed email on change password page is not valid: %s",b)}}},X=function(a){for(var b=B.split(","),c=0;c<b.length;c++)if(l(a,"@"+b[c].trim()))return!0;return!1},T=function(){if(1==E||0==E)return E;for(var a=document.documentElement.innerHTML.slice(0,12E4),b=0;b<F.length;b++)if(0<=a.indexOf(F[b]))return E=
!0;return E=!1},ka=function(){for(var a=document.documentElement.innerHTML.slice(0,12E4),b=0;b<G.length;b++)if(0<=a.indexOf(G[b]))return!0;return!1},Q=function(){var a=I.match(da)[3]||null;a=(a?decodeURI(a):a)||"";for(var b=0;b<H.length;b++){var c=H[b];if(a==c)return!0;var d=c;h(c,".")||(d="."+d);if(l(a,d))return!0}return!1},Y=function(){N=!0;h(I,"https://accounts.google.com/")&&(new MutationObserver(S)).observe(document.body,{attributes:!0,childList:!0,characterData:!0});S()},Z=location.href.toString();
"about:blank"==Z?(I=window.parent.location.href,J=""):(I=Z,J=document.referrer.toString());
chrome.storage.onChanged.addListener(function(a,b){if("managed"==b){b=function(a,b){return a.filter(function(a){return 0>b.indexOf(a)})};for(var c in a){L||(L=!0);var d=a[c].newValue,f=a[c].oldValue;switch(c){case "corp_email_domain":B=d.replace(/@/g,"").toLowerCase();break;case "corp_html":F=b(F,f);Array.prototype.push.apply(F,d);break;case "corp_html_tight":G=b(G,f);Array.prototype.push.apply(G,d);break;case "security_email_address":C=d;break;case "sso_form_selector":y=d;break;case "sso_password_selector":z=
d;break;case "sso_url":x=d;break;case "sso_username_selector":A=d;break;case "whitelist_top_domains":H=b(H,f.filter(String)),Array.prototype.push.apply(H,d.filter(String))}}}});
(function(a){chrome.storage.managed.get(function(b){0==Object.keys(b).length?L=!1:(L=!0,B=b.corp_email_domain.replace(/@/g,"").toLowerCase(),C=b.security_email_address,y=b.sso_form_selector,z=b.sso_password_selector,x=b.sso_url,A=b.sso_username_selector,b.whitelist_top_domains&&Array.prototype.push.apply(H,b.whitelist_top_domains.filter(String)),b.corp_html&&Array.prototype.push.apply(F,b.corp_html),b.corp_html_tight&&Array.prototype.push.apply(G,b.corp_html_tight));M=!0;a()})})(S);
window.addEventListener("keypress",U,!0);window.addEventListener("keydown",V,!0);window.addEventListener("paste",W,!0);chrome.runtime.onMessage.addListener(function(a){K=!1;R(a)});document.addEventListener("DOMContentLoaded",Y);"interactive"!=document.readyState&&"complete"!=document.readyState&&"loaded"!=document.readyState||Y();
